services:
  kota-mcp:
    build: .
    container_name: kota-mcp-gateway
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=8081
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ~/.kota:/root/.kota:ro
    healthcheck:
      test: ["CMD", "node", "scripts/health-check.js"]
      interval: 30s
      timeout: 3s
      retries: 3
