version: '3.8'
services:
  kota-mcp:
    build: .
    container_name: kota-mcp-gateway
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ~/.kota:/root/.kota:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

